// Generates src/lib/powiat-shapes.ts: simplified SVG outlines of the 22 Małopolska powiats.
// Source: ppatrzyk/polska-geojson (converted from GUGiK PRG, public data without fees).
// Run: pnpm tsx scripts/build-powiat-shapes.ts
import { writeFileSync } from 'node:fs';
import { POWIAT_TILES } from '../src/lib/powiats';

const SOURCE =
	'https://raw.githubusercontent.com/ppatrzyk/polska-geojson/master/powiaty/powiaty-medium.geojson';
const WIDTH = 800;
/** Douglas-Peucker tolerance in output pixels */
const TOLERANCE = 0.7;
// "brzeski" and others exist in several voivodeships: keep features centred in Małopolska.
const BBOX = { lon: [19.0, 21.5], lat: [49.1, 50.6] };

type Pt = [number, number];
type Ring = Pt[];
type Feature = {
	properties: { nazwa: string };
	geometry:
		{ type: 'Polygon'; coordinates: Ring[] } | { type: 'MultiPolygon'; coordinates: Ring[][] };
};

// City powiats are named after the city ("powiat Kraków"), others by adjective ("powiat bocheński").
const featureName = (p: (typeof POWIAT_TILES)[number]) => `powiat ${p.name}`;

function polygons(f: Feature): Ring[][] {
	return f.geometry.type === 'Polygon' ? [f.geometry.coordinates] : f.geometry.coordinates;
}

function mean(points: Pt[]): Pt {
	const s = points.reduce((a, p) => [a[0] + p[0], a[1] + p[1]], [0, 0]);
	return [s[0] / points.length, s[1] / points.length];
}

function simplify(points: Pt[], tol: number): Pt[] {
	if (points.length < 3) return points;
	const [a, b] = [points[0], points[points.length - 1]];
	let maxD = 0;
	let idx = 0;
	for (let i = 1; i < points.length - 1; i++) {
		const d = segDist(points[i], a, b);
		if (d > maxD) [maxD, idx] = [d, i];
	}
	if (maxD <= tol) return [a, b];
	return [
		...simplify(points.slice(0, idx + 1), tol).slice(0, -1),
		...simplify(points.slice(idx), tol)
	];
}

function segDist(p: Pt, a: Pt, b: Pt): number {
	const [dx, dy] = [b[0] - a[0], b[1] - a[1]];
	const len = dx * dx + dy * dy;
	const t = len ? Math.max(0, Math.min(1, ((p[0] - a[0]) * dx + (p[1] - a[1]) * dy) / len)) : 0;
	return Math.hypot(p[0] - (a[0] + t * dx), p[1] - (a[1] + t * dy));
}

function inside(p: Pt, rings: Ring[]): boolean {
	let c = false;
	for (const r of rings)
		for (let i = 0, j = r.length - 1; i < r.length; j = i++) {
			const [xi, yi] = r[i];
			const [xj, yj] = r[j];
			if (yi > p[1] !== yj > p[1] && p[0] < ((xj - xi) * (p[1] - yi)) / (yj - yi) + xi) c = !c;
		}
	return c;
}

/** Point inside the shape farthest from its edges: where the label fits best. */
function labelPoint(rings: Ring[]): Pt {
	const all = rings.flat();
	const xs = all.map((p) => p[0]);
	const ys = all.map((p) => p[1]);
	const [x0, x1, y0, y1] = [Math.min(...xs), Math.max(...xs), Math.min(...ys), Math.max(...ys)];
	let best: Pt = mean(all);
	let bestD = -1;
	const N = 60;
	for (let i = 0; i <= N; i++)
		for (let j = 0; j <= N; j++) {
			const p: Pt = [x0 + ((x1 - x0) * i) / N, y0 + ((y1 - y0) * j) / N];
			if (!inside(p, rings)) continue;
			let d = Infinity;
			for (const r of rings)
				for (let k = 1; k < r.length; k++) d = Math.min(d, segDist(p, r[k - 1], r[k]));
			if (d > bestD) [best, bestD] = [p, d];
		}
	return best;
}

const geo = (await (await fetch(SOURCE)).json()) as { features: Feature[] };
const inBox = (f: Feature) => {
	const [lon, lat] = mean(polygons(f).flat(2));
	return lon > BBOX.lon[0] && lon < BBOX.lon[1] && lat > BBOX.lat[0] && lat < BBOX.lat[1];
};
const picked = POWIAT_TILES.map((p) => {
	const f = geo.features.find((f) => f.properties.nazwa === featureName(p) && inBox(f));
	if (!f) throw new Error(`no shape for ${p.name}`);
	return { p, f };
});

// Equirectangular projection around the region's mean latitude.
const lonLat = picked.flatMap(({ f }) => polygons(f).flat(2));
const minLon = Math.min(...lonLat.map((p) => p[0]));
const maxLon = Math.max(...lonLat.map((p) => p[0]));
const maxLat = Math.max(...lonLat.map((p) => p[1]));
const minLat = Math.min(...lonLat.map((p) => p[1]));
const k = Math.cos((((minLat + maxLat) / 2) * Math.PI) / 180);
const scale = WIDTH / ((maxLon - minLon) * k);
const HEIGHT = Math.ceil((maxLat - minLat) * scale);
const project = ([lon, lat]: Pt): Pt => [(lon - minLon) * k * scale, (maxLat - lat) * scale];
const r1 = (n: number) => Math.round(n * 10) / 10;

const shapes = picked.map(({ p, f }) => {
	const rings = polygons(f).flatMap((poly) =>
		poly.map((ring) => simplify(ring.map(project), TOLERANCE))
	);
	const d = rings
		.filter((r) => r.length >= 3)
		.map((r) => 'M' + r.map(([x, y]) => `${r1(x)} ${r1(y)}`).join('L') + 'Z')
		.join('');
	const [lx, ly] = labelPoint(rings);
	return { teryt: p.teryt, d, label: [r1(lx), r1(ly)] as Pt };
});

writeFileSync(
	'src/lib/powiat-shapes.ts',
	`// Generated by scripts/build-powiat-shapes.ts from GUGiK PRG boundaries (via ppatrzyk/polska-geojson).
// Do not edit by hand.
export const MAP_SIZE = { width: ${WIDTH}, height: ${HEIGHT} } as const;

export type PowiatShape = { teryt: string; d: string; label: [number, number] };

export const POWIAT_SHAPES: PowiatShape[] = ${JSON.stringify(shapes, null, '\t')};
`
);
console.log(`wrote ${shapes.length} shapes, ${WIDTH}x${HEIGHT}`);
